//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.09 at 02:46:02 PM CDT 
//


package com.springboot.example.springwebservice.consumingwebservice.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.springboot.example.springwebservice.consumingwebservice.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.springboot.example.springwebservice.consumingwebservice.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IsValidISBN13 }
     * 
     */
    public IsValidISBN13 createIsValidISBN13() {
        return new IsValidISBN13();
    }

    /**
     * Create an instance of {@link IsValidISBN13Response }
     * 
     */
    public IsValidISBN13Response createIsValidISBN13Response() {
        return new IsValidISBN13Response();
    }

    /**
     * Create an instance of {@link IsValidISBN10 }
     * 
     */
    public IsValidISBN10 createIsValidISBN10() {
        return new IsValidISBN10();
    }

    /**
     * Create an instance of {@link IsValidISBN10Response }
     * 
     */
    public IsValidISBN10Response createIsValidISBN10Response() {
        return new IsValidISBN10Response();
    }

}
