//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.09 at 02:46:02 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.daehosting.com/ISBN", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.springboot.example.springwebservice.consumingwebservice.wsdl;
